// <auto-generated />
using System;
using APIPrevisaoTempo.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIPrevisaoTempo.WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190526214623_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("APIPrevisaoTempo.WebApi.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country")
                        .HasMaxLength(3);

                    b.Property<string>("CustomCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<double?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CustomCode")
                        .IsUnique();

                    b.ToTable("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
